### ISSUE TITLE
All errors are grouped under "SomeException"

### ISSUE THREAD

**Issue by emhoracek** [tfausak/ratel-wai#1]
Then the actual exception is listed in the "Message" section.

This means I'm not notified for any exceptions after the first one.

The way I'd like to solve this is by including the first ~30 characters of the exception message in the title. That way very similar exceptions do get grouped, but very different exceptions are no longer grouped.

**Comment by tfausak** [comment]
I haven't used or looked at this project in a while, so it took me a minute to figure out what's going on here. Ratel uses [`typeOf`](https://www.stackage.org/haddock/lts-8.22/base-4.9.1.0/Data-Typeable.html#v:typeOf) to get the type of the exception. That part is fine; the problem is actually here in ratel-wai. 

This project uses [`catch`](https://www.stackage.org/haddock/lts-8.22/base-4.9.1.0/Control-Exception.html#v:catch) to catch *all* exceptions, report them to Honeybadger, and re-throw them. The problem is that `catch` uses the type to select which exceptions to catch. In order to catch all exceptions, it's necessary to catch `SomeException`. That, of course, makes `typeOf` return `SomeException`. 

So while https://github.com/tfausak/ratel/pull/3 will definitely work, it's kind of a workaround. What this project needs is a way to catch all exceptions but keep their original type information. I'm not familiar enough with Haskell's exceptions to say if that exists, or even if it's possible.

**Comment by emhoracek** [comment]
Yeah, I figured out that was the problem but I couldn't find any way to fix it. 😞 That's why I went for the exception message work-around. I've been using a fork with this work-around for over a year now in production, but upgrading that project to GHC 8 made me realize I ought to ask you about it.

I can imagine that you don't want this weird hacky work-around in your actual library, but maybe instead ratel or ratel-wai could allow users to pass in the way they want exceptions to be rendered? :thinking: I would also be very happy if we could figure out a way to make `typeOf` work instead.

I want to add that there's no hurry. I can continue using my fork until there's a good solution.

**Comment by tfausak** [comment]
I think I got `typeOf` (more) working over at https://github.com/tfausak/ratel/pull/3#issuecomment-315609397. 

Ratel is pretty open, but ratel-wai doesn't really let you configure anything. Seems like it would be nice to pass a `Payload -> IO Payload` function to `ratelMiddleware`. That way you could actually fill out the server information and such. As a bonus it would let you do whatever you want to the error, including adding some more stuff to it.

**Comment by emhoracek** [comment]
Really happy with the `Payload` modifier argument solution. Thanks!
